name: Ubuntu Cloud Image
on:
  push:
    branches:
      - master

jobs:
  build:
    name: ubuntu-bionic-generic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Required
        run: |
          sudo apt-get update
          sudo apt-get install -yqq debootstrap
      - name: Building
        run: sudo ./make_image.bash
