name: Ubuntu Cloud Image
on:
  push:
    branches:
      - master

jobs:
  build:
    name: ubuntu-bionic-generic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
